language: node_js
node_js:
  - '10'
before_script:
  - npm run lint
  - npm run build
cache: npm
deploy:
  script:
    - npm run deploy
  after_script:
    - npm run alias
  skip_cleanup: true
  on:
    branch: master
