language: node_js
node_js:
  - '10'
script:
  - npm run lint
  - npm run build
cache: npm
deploy:
  provider: script
  script:
    - npm run deploy
    - npm run alias
  skip_cleanup: true
  on:
    branch: master
